// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asdtekdxduthpyfisdwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzZHRla2R4ZHV0aHB5ZmlzZHdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDIyMjQsImV4cCI6MjA2MTIxODIyNH0.hZ80ysCci6Yv2B2_eIlCX3iQ3xOGnry8DBQxXvbrd78";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);